### ISSUE TITLE
osc disappears when cycling through playlist

### ISSUE THREAD

**Issue by Twhite90100** [TheAMM/mpv_thumbnail_script#47]
When I'm quickly going through a playlist, there's a high chance that when changing file the osc will disappear to never show up again.

**Comment by eternalcakes** [comment]
Facing exactly the same problem. I believe what's happening is that the thumbnail script is breaking when we change file, and because osc=no in main config file, it completely disappears and cannot be pulled from anywhere.

Given that this hasn't been updated since 2018, we may have to find another way to get thumbnails :(

**Comment by eternalcakes** [comment]
Been talking to this guy and he fixed the script for us! Something about the duration check causing issues. Find the fix here; just overwrite the old file! (Don't need to copy anything else, just the thumbnail script)

https://github.com/Tsubajashi/mpv-settings/tree/master/scripts

**Comment by TheAMM** [comment]
This was fixed in November in e0225de.

**Comment by Jerrk** [comment]
This has not been fixed for me.

removed the old .lua scripts, replacing them with v0.4.2.
deleted the old config and made a new one (in case it changed for some reason)
I am still getting this issue.
heres a quick vid of the issue
https://streamable.com/s/nf27g/iispvn

**Comment by blankname** [comment]
@Jerrk 
You need to use master.

The most recent release doesn't contain the fix (0.4.2 is from Feb 2018).

**Comment by Jerrk** [comment]
oh whoops i read that as 2020 somehow, my bad

edit: 
Master certainly works better but if i scrub through several files in a larger playlist (20~) it instantly breaks.
this does not seem to be a problem if i skip files, but if i scrub through the file and reach the end on loadup of the next file osc breaks.

**Comment by blankname** [comment]
@Jerrk 
Any error message/logs like the OP of #51 posted?

**Comment by Jerrk** [comment]
I think this is the relevant information
![](https://i.imgur.com/OymKPVD.png)

```
[   0.003][v][cplayer] mpv 0.31.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
[   0.003][v][cplayer]  built on Fri Jan 10 16:14:05 STD 2020
[   0.003][v][cplayer] ffmpeg library versions:
[   0.003][v][cplayer]    libavutil       56.31.100
[   0.003][v][cplayer]    libavcodec      58.54.100
[   0.003][v][cplayer]    libavformat     58.29.100
[   0.003][v][cplayer]    libswscale      5.5.100
[   0.003][v][cplayer]    libavfilter     7.57.100
[   0.003][v][cplayer]    libswresample   3.5.100
[   0.003][v][cplayer] ffmpeg version: n4.2.1-1-ge130ee1eb5
````
Edit: updated mpv to a more recent version, still same problem

```
[   0.004][v][cplayer] mpv 0.32.0-201-ge7bab0025f Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[   0.005][v][cplayer]  built on Sun Mar  1 14:21:15 +08 2020
[   0.005][v][cplayer] FFmpeg library versions:
[   0.005][v][cplayer]    libavutil       56.42.100
[   0.005][v][cplayer]    libavcodec      58.73.102
[   0.005][v][cplayer]    libavformat     58.39.101
[   0.005][v][cplayer]    libswscale      5.6.100
[   0.005][v][cplayer]    libavfilter     7.77.100
[   0.005][v][cplayer]    libswresample   3.6.100
[   0.005][v][cplayer] FFmpeg version: git-2020-02-29-8f3df1dd4
```
![](https://i.imgur.com/xA7v6S4.png)

**Comment by blankname** [comment]
@Jerrk Please try my branch at #54 
or https://github.com/blankname/mpv_thumbnail_script/tree/misc
